<div id="Carrossel" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#Carrossel" data-slide-to="0" class="active"></li>
        <li data-target="#Carrossel" data-slide-to="1"></li>
        <li data-target="#Carrossel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <svg class="bd-placeholder-img" width="100%" height="100%" focusable="false" role="img"><rect width="100%" height="100%" fill="#333"/></svg>
            <div class="container">
                <div class="carousel-caption text-left">
                    <h1>Cadastro</h1>
                    <p>Experimente nossos serviços.</p>
                    <p><a class="btn btn-lg btn-warning" href="../php/cadastro_cliente.php" role="button">Cadastre-se</a></p>
              </div>
            </div>
        </div>
        <div class="carousel-item">
            <svg class="bd-placeholder-img" width="100%" height="100%" focusable="false" role="img"><rect width="100%" height="100%" fill="#333"/></svg>
            <div class="container">
                <div class="carousel-caption">
                    <h1>Marketing</h1>
                    <p>A divulgação de seu negócio nunca esteve tão fácil.</p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <svg class="bd-placeholder-img" width="100%" height="100%" focusable="false" role="img"><rect width="100%" height="100%" fill="#333"/></svg>
            <div class="container">
                <div class="carousel-caption text-right">
                    <h1>Cupons</h1>
                    <p>Preços que cabem no seu bolso.</p>
                    <p><a class="btn btn-lg btn-warning" href="../php/cuponsCadastrados.php" role="button">Comprar</a></p>
                </div>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#Carrossel" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    </a>
    <a class="carousel-control-next" href="#Carrossel" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
    </a>
</div>
