<div class="container">
    <div class="row">
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom1.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Vale compra - Loja X</h5></p>
               <h4 class="card-title">Desconto: 10%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$110,00</h5>Por:
                    <h5 class="novoValor">R$99,00</h5>
                </div>
                <p class="card-text ">Vale compra de até R$110,00.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-warning">Expirado</button>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom5.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Lava Rapido - AutoCar</h5></p>
               <h4 class="card-title">Desconto: 20%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$100,00</h5>Por:
                    <h5 class="novoValor">R$80,00</h5>
                </div>
                <p class="card-text ">Vale uma lavagem completa.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-warning">Expirado</button>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>

    </div>
</div>
