<div class="container">
    <div class="row">
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm" height="10%">
            <img  src="../imgCupom/cupom6.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Desconto - Restaurante X</h5></p>
                <h5 class="card-title">R$100,00</h5>
                <p class="card-text ">Desconto no prato principal.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-warning">Remover</button>
                  <button type="button" class="btn btn-sm btn-outline-warning">Editar</button>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm" height="10%">
            <img  src="../imgCupom/cupom7.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Desconto - Restaurante X</h5></p>
                <h5 class="card-title">R$70,00</h5>
                <p class="card-text ">Desconto no à la carte.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-warning">Remover</button>
                  <button type="button" class="btn btn-sm btn-outline-warning">Editar</button>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>
    </div>
</div>
    </main>
</div>
