<div class="container">
    <div class="row">
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom1.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Compre qualquer produto do nosso estabelecimento</h5></p>
                <h5 class="card-title">R$110,00</h5>
                <p class="card-text ">Use seu cupom e aproveite todos os nossos produtos</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-warning">Utilizado</button>
                </div>
                <small class="text-muted">21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom5.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Lava Rapido do se Jair</h5></p>
                <h5 class="card-title">R$45,00</h5>
                <p class="card-text ">Compre o nosso cupom e e deixe o seu carro limpinho</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-warning">Utilizado</button>
                </div>
                <small class="text-muted">21/04</small>
            </div>
            </div>
        </div>
        </div>

    </div>
</div>