<div class="container">
    <div class="row">
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm" height="10%">
            <img  src="../imgCupom/cupom6.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Jantar para duas pessoas no restaurante Bom Gosto</h5></p>
                <h4 class="card-title">Desconto: 20%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$100,00</h5>Por:
                    <h5 class="novoValor">R$80,00</h5>
                </div>
                <p class="card-text ">Ganhe um super desconto em seu jantar</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-warning">Remover</button>
                  <button type="button" class="btn btn-sm btn-outline-warning">Editar</button>
                </div>
                <small class="text-muted">21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm" height="10%">
            <img  src="../imgCupom/cupom7.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Almoce com a gente!!!</h5></p>
                 <h4 class="card-title">Desconto: 10%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$70,00</h5>Por:
                    <h5 class="novoValor">R$63,00</h5>
                </div>                 
                <p class="card-text ">Ganhe um super desconto em seu almoço e aproveite</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-warning">Remover</button>
                  <button type="button" class="btn btn-sm btn-outline-warning">Editar</button>
                </div>
                <small class="text-muted">21/04</small>
            </div>
            </div>
        </div>
        </div>
    </div>
</div>
    </main>
</div>