<div class="row">
    <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
        <img  src="../imgCupom/cupom1.jpg">
        <div class="card-body">
        <p class="card-text"><h5 class="card-title">Vale compra - Loja X</h5></p>
            <h5 class="card-title">R$110,00</h5>
            <p class="card-text ">Vale compra de até R$110,00.</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
            </div>
            <small class="text-muted">Expira em: 21/04</small>
        </div>
        </div>
    </div>
    </div>
    <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
        <img  src="../imgCupom/cupom2.jpg">
        <div class="card-body">
        <p class="card-text"><h5 class="card-title">Cesta de frutas - Varejão Y</h5></p>
            <h5 class="card-title">R$35,00</h5>
            <p class="card-text ">Uma unidade de cesta de frutas.</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
            </div>
            <small class="text-muted">Expira em: 21/04</small>
        </div>
        </div>
    </div>
    </div>
    <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
        <img  src="../imgCupom/cupom3.jpg">
        <div class="card-body">
        <p class="card-text"><h5 class="card-title">Pacote de serviços -  Salão da Luz</h5></p>
            <h5 class="card-title">R$75,00</h5>
            <p class="card-text ">Qualquer serviço com desconto.</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
            </div>
            <small class="text-muted">Expira em: 21/04</small>
        </div>
        </div>
    </div>
    </div>
    <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
        <img  src="../imgCupom/cupom4.jpg">
        <div class="card-body">
        <p class="card-text"><h5 class="card-title">Serviços - PetShop AU&MIAU</h5></p>
            <h5 class="card-title">R$80,00</h5>
            <p class="card-text ">Rações, banho e tosa.</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
            </div>
            <small class="text-muted">Expira em: 21/04</small>
        </div>
        </div>
    </div>
    </div>
    <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
        <img  src="../imgCupom/cupom5.jpg">
        <div class="card-body">
        <p class="card-text"><h5 class="card-title">Lava rápido - AutoCar</h5></p>
            <h5 class="card-title">R$45,00</h5>
            <p class="card-text ">Vale uma lavagem completa.</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
            </div>
            <small class="text-muted">Expira em: 21/04</small>
        </div>
        </div>
    </div>
    </div>
    <div class="col-md-4">
    <div class="card mb-4 shadow-sm">
        <img  src="../imgCupom/cupom6.jpg">
        <div class="card-body">
        <p class="card-text"><h5 class="card-title">Desconto - Restaurante X</h5></p>
            <h5 class="card-title">R$100,00</h5>
            <p class="card-text ">Desconto no prato principal.</p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
            </div>
            <small class="text-muted">Expira em: 21/04</small>
        </div>
        </div>
    </div>
    </div>
</div>
