<div class="container">
    <div class="row">
         <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom1.jpg">
            <div class="card-body">
                <p class="card-text"><h5 class="card-title">Compre qualquer produto do nosso estabelecimento</h5></p>
                <h4 class="card-title">Desconto: 10%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$110,00</h5>Por:
                    <h5 class="novoValor">R$99,00</h5>
                </div>
                <p class="card-text ">Use seu cupom e aproveite todos os nossos produtos</p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                    </div>
                    <small class="text-muted">21/04</small>
                </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom2.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Cesta de Frutas da Dona Maria</h5></p>
                <h4 class="card-title">Desconto: 15%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$45,00</h5>Por:
                    <h5 class="novoValor">R$38,25</h5>
                </div>
                <p class="card-text ">Aproveite o cupom de desconto e compre uma bela cesta de frutas</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom3.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Pacote de serviços do salão da Luz</h5></p>
                <h4 class="card-title">Desconto: 15%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$65,00</h5>Por:
                    <h5 class="novoValor">R$55,25</h5>
                </div>
                <p class="card-text ">Faça qualquer procedimento com o cupom de desconto</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom4.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Todos os serviços do PetShop AU&MIAU</h5></p>
                <h4 class="card-title">Desconto: 20%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$50,00</h5>Por:
                    <h5 class="novoValor">R$40,00</h5>
                </div>
                <p class="card-text ">Rações, banho e tosa, e tudo que seu animalzinho merece</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm" height="10%">
            <img  src="../imgCupom/cupom7.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Almoce com a gente!!!</h5></p>
                <h4 class="card-title">Desconto: 10%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$70,00</h5>Por:
                    <h5 class="novoValor">R$63,00</h5>
                </div>               
                <p class="card-text ">Ganhe um super desconto em seu almoço e aproveite</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom5.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Lava Rapido do se Jair</h5></p>
                <h4 class="card-title">Desconto: 5%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$45,00</h5>Por:
                    <h5 class="novoValor">R$42,75</h5>
                </div>
               <p class="card-text ">Cmpre o nosso cupom e e deixe o seu carro limpinho</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">21/04</small>
            </div>
            </div>
        </div>
        </div>
       <div class="col-md-4">
        <div class="card mb-4 shadow-sm" height="10%">
            <img  src="../imgCupom/cupom6.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Jantar para duas pessoas no restaurante Bom Gosto</h5></p>
                <h4 class="card-title">Desconto: 20%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$100,00</h5>Por:
                    <h5 class="novoValor">R$80,00</h5>
                </div>
                <p class="card-text ">Ganhe um super desconto em seu jantar</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">21/04</small>
            </div>
            </div>
        </div>
        </div>
    </div>
</div>