<div class="container">
    <div class="row">
         <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom1.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Vale compra - Loja X</h5></p>
                <h4 class="card-title">Desconto: 10%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$110,00</h5>Por:
                    <h5 class="novoValor">R$99,00</h5>
                </div>
                <p class="card-text ">Vale compra de até R$110,00.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom2.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Cesta de frutas - Varejão Y</h5></p>
                 <h4 class="card-title">Desconto: 15%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$45,00</h5>Por:
                    <h5 class="novoValor">R$38,25</h5>
                </div>
                <p class="card-text ">Aproveite o cupom de desconto e compre uma unidade de cesta de frutas.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom3.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Pacote de serviços -  Salão da Luz</h5></p>
               <h4 class="card-title">Desconto: 15%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$65,00</h5>Por:
                    <h5 class="novoValor">R$55,25</h5>
                </div>
                <p class="card-text ">Faça qualquer procedimento com o cupom de desconto.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom4.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Serviços - PetShop AU&MIAU</h5></p>
               <h4 class="card-title">Desconto: 20%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$50,00</h5>Por:
                    <h5 class="novoValor">R$40,00</h5>
                </div>
                <p class="card-text ">Rações, banho e tosa.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm" height="10%">
            <img  src="../imgCupom/cupom7.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Almoce com a gente!!!</h5></p>
                <h4 class="card-title">Desconto: 10%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$70,00</h5>Por:
                    <h5 class="novoValor">R$63,00</h5>
                </div>               
                <p class="card-text ">Ganhe um super desconto em seu almoço e aproveite</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>
        <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <img  src="../imgCupom/cupom5.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Lava rápido - AutoCar</h5></p>
                 <h4 class="card-title">Desconto: 5%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$45,00</h5>Por:
                    <h5 class="novoValor">R$42,75</h5>
                </div>
                <p class="card-text ">Vale uma lavagem completa.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>
       <div class="col-md-4">
        <div class="card mb-4 shadow-sm" height="10%">
            <img  src="../imgCupom/cupom6.jpg">
            <div class="card-body">
            <p class="card-text"><h5 class="card-title">Desconto - Restaurante X</h5></p>
                <h4 class="card-title">Desconto: 20%</h4>
                <div class="card-title">De:
                    <h5 class="valor">R$100,00</h5>Por:
                    <h5 class="novoValor">R$80,00</h5>
                </div>
                <p class="card-text ">Desconto no prato principal.</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a href="#"style="background-color:#FFDB58; color:white;"class="btn btn-warning btn-lg">Comprar</a>
                </div>
                <small class="text-muted">Expira em: 21/04</small>
            </div>
            </div>
        </div>
        </div>
    </div>
</div>
