<header>
    <nav class="navbar navbar-expand-md navbar-light fixed-top">
        <a class="navbar-brand" href="../index.php">
            <img src="../images/logo.png" width="55" height="45"/>
            Encontre
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="nav navbar-nav ml-auto">
                <ul class="navbar-nav">
                    <li>
                        <button style="background-color: #fede59" type="button" class="btn" data-toggle="modal" data-target="#ModalSobre">
                            <span class="material-icons">contact_support</span>
                            Sobre
                        </button>
                    </li>
                    <li>
                        <button style="background-color: #fede59" type="button" class="btn" data-toggle="modal" data-target="#ModalContato">
                            <span class="material-icons">alternate_email</span>
                            Contato
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="modal fade" id="ModalSobre" tabindex="-1" role="dialog" aria-labelledby="ModalSobreTitulo" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ModalSobreTitulo2">&nbsp;Sobre</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>
                        Aplicação web de compra e marketing online que possibilita benefícios mútuos na
                        relação entre microempresas e clientes. A aplicação possibilita que o cliente realize
                        compras de cupons de descontos, como também, ao divulgar links promocionais de outras
                        empresas ganhe uma taxa do lucro obtido das compras efetuadas através do link divulgado.
                        Podendo também acumular creditos na plataforma a partir de um determinado nível de compras no site. Diante
                        disso, a aplicação tem como objetivo o impulsionamento na visibilidade da empresa através de
                        seus próprios clientes, visando a diminuição do impacto causado nas transações de mercado derivado
                        do período de crise provocado pelo COVID-19.
                    </p>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</header>
