<header>
<nav class="navbar navbar-expand-md navbar-dark fixed-top"
style="background-color:#FF8C00;">
<a class="navbar-brand" href="index.php">Projeto</a>
<button class="navbar-toggler" type="button" datatoggle="
collapse" data-target="#navbarCollapse" ariacontrols="
navbarCollapse" aria-expanded="false" aria-label="Toggle
navigation">
<span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarCollapse">
<ul class="navbar-nav mr-auto">
<li class="nav-item active">
<a class="nav-link"
href="../php/cuponsCadastrados.php">Cupons Cadastrados</a>
</li>
<li class="nav-item active">
<a class="nav-link"
href="../php/cadastroCupons.php">Cadastrar Cupons</a>
</li>
</ul>
</div>
<div class="collapse navbar-collapse" id="navbarCollapse">
<div class="nav navbar-nav ml-auto">
<ul class="navbar-nav">
<li class="nav-item">
<a class="nav-link" href="#">
<span class="materialicons">
account_circle</span> Perfil </a>
</li>
</ul>
</div>
</div>
</nav>
</header>