<header>
    <nav class="navbar navbar-expand-md navbar-light fixed-top">
        <a class="navbar-brand" href="../index.php">Projeto</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="nav navbar-nav ml-auto">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <button style="background-color: #FFD700" type="button" class="btn" data-toggle="modal" data-target="#ModalLogin">
                            <span class="material-icons">account_circle</span>
                            Login
                        </button>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
