<div class="modal fade" id="ModalContato" tabindex="-1" role="dialog" aria-labelledby="ModalContatoTitulo" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="ModalContatoTitulo2">&nbsp;Contato</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <b><p>Desenvolvedores</p></b>
          <p>
              Renan Dias - martins.dias@aluno.ifsp.edu.br<br/>
              Amália Melo - amalia.melo@aluno.ifsp.edu.br<br/>
              Amanda Campezan - amanda.campezan@aluno.ifsp.edu.br<br/>
          </p>
          <hr>
          <b><p>Orientador</p></b>
          <p>
              José Rodolfo Beluzo - jrbeluzo@ifsp.edu.br
          </p>
      </div>
    </div>
  </div>
</div>
