<div class="row">
    <nav class="col-md-2 bg-light">
        <div class="sidebar-sticky">
            <ul class="nav flex-column" >
                <li class="nav-item" >
                    <a class="nav-link active" href="homeUsuario.php">
                        <span class="material-icons">home</span>
                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span class="material-icons">payment</span>
                        Seus Cupons
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">
                        <span class="material-icons">equalizer</span>
                        Seu lucro
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="perfil_cliente.php">
                        <span class="material-icons">person_outline</span>
                        Perfil
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</div>
