<footer class="page-footer container">
    <p class="float-right">
        <button type="button" class="btn btn-link" data-toggle="modal" data-target="#ModalContato">
            Contato
        </button>
    </p>
    <p>&copy; 2020 Instituto Federal de São Paulo, Araraquara</p>
    <p style="font-size:8px;"><a href="https://www.freepik.com/free-photos-vectors/sale">Icones e-commerce criados por photoroyalty - www.freepik.com</a></p>
    <p style="font-size:8px;">Ícones feitos por <a href="https://www.flaticon.com/br/autores/kiranshastry" title="Kiranshastry">Kiranshastry</a> de <a href="https://www.flaticon.com/br/" title="Flaticon"> www.flaticon.com</a> </p>
  </footer>
