<footer class="container">
    <p class="float-right">&middot;
        <button type="button" class="btn btn-link" data-toggle="modal" data-target="#ModalContato">
            Contato
        </button>
    </p>
    <p>&copy; 2020 Instituto Federal de São Paulo, Araraquara</p>
    <p style="font-size:8px;"><a href="https://www.freepik.com/free-photos-vectors/sale">Icones e-commerce criados por photoroyalty - www.freepik.com</a></p>
  </footer>
