<footer class="footer page-footer container-fluid">
    <div class="inner">
        <div class="row">
            <div class="col-lg-6 col-sm-6">
                <p>&copy; 2020 Instituto Federal de São Paulo, Araraquara</p>
                <p style="font-size:8px;"><a href="https://www.freepik.com/free-photos-vectors/sale">Icones e-commerce criados por photoroyalty - www.freepik.com</a></p>
                <p style="font-size:8px;">Ícones feitos por <a href="https://www.flaticon.com/br/autores/kiranshastry" title="Kiranshastry">Kiranshastry</a> de <a href="https://www.flaticon.com/br/" title="Flaticon"> www.flaticon.com</a> </p>
                <p style="font-size:8px;">Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon"> www.flaticon.com</a></p>
            </div>
            <div class="col-lg-6 col-sm-6">
                <div class="float-right">
                    <button type="button" class="btn btn-link" data-toggle="modal" data-target="#ModalContato">
                        Contato
                    </button>
                </div>
            </div>
        </div>
    </div>
</footer>
